package CampañaVacunacion;

public enum Provincia {
    BUENOS_AIRES, CHACO, RIO_NEGRO, FORMOSA, LA_PAMPA, NEUQUEN, SALTA, JUJUY, TIERRA_DEL_FUEGO, SANTIAGO_DEL_ESTERO,
    SANTA_FE, SANTA_CRUZ, MENDOZA, CORDOBA, TUCUMAN, CHUBUT, CORRIENTES, ENTRE_RIOS, MISIONES, SAN_JUAN,
    LA_RIOJA, CATAMARCA, SAN_LUIS

}